services:
  postgres:
    container_name: database
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    container_name: localstack
    image: localstack/localstack:4
    restart: unless-stopped
    environment:
      - SERVICES=sqs,events
      - DEBUG=0
      - AWS_DEFAULT_REGION=eu-west-1
      - EXTRA_CORS_ALLOWED_ORIGINS=https://app.localstack.cloud
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - ./docker/localstack-init:/etc/localstack/init/ready.d

volumes:
  postgres_data:
    driver: local
  localstack_data:
    driver: local
