name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        id: pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Biome check
        run: pnpm run check

      - name: Architecture check
        run: pnpm run arch

      - name: Dead code check
        run: pnpm run dead

      - name: Tests
        run: pnpm run test

      - name: Build
        run: pnpm run build